### ISSUE TITLE
Begin Node CRUD Example doesn't work locally

### ISSUE THREAD

**Issue by wesbos** [smallwins/begin-issues#15]
Locally the Begin CRUD app doesn't work locally. 

**Steps to reproduce**
1. Create a new begin Node CRUD app
2. clone locally from your github
3. `npm install`
4. `npm start`
5. open localhost:3333
6. Try to add a todo in the successfully rendered UI
7. Times out after 5 seconds and shows an error

I notice that I also get `  "message": "Missing credentials in config",` error now. Maybe after I added some things on the begin.com hosted site?

Is this supposed to work locally? 

<img width="795" alt="Screen Shot 2020-02-05 at 3 28 36 PM" src="https://user-images.githubusercontent.com/176013/73880399-60eb0f80-482c-11ea-8e42-517b97c82847.png">

**Comment by brianleroux** [comment]
its def supposed to work! wasn't able to reproduce this but I think that is because I have aws credentials in `~/.aws/credentials`. (under the hood everything is vanilla aws and deployable without us …but this means we sometimes inherit undesirable experiences from our good friend the`aws-sdk`) 

gonna nuke my creds and get this reproducing now but wanted to ping back to let you know we're on it!

**Comment by wesbos** [comment]
👌  thanks

**Comment by wesbos** [comment]
If it helps, I have a ~/.aws/config that is about 3 years old - I haven't used AWS in about that long too

**Comment by brianleroux** [comment]
I do not blame u. =)

Just confirmed it. Quick workaround to work local create this file `~/.aws/credentials`

```
[default]
aws_access_key_id=xxx
aws_secret_access_key=xxx
```

I'll see about patching our sandbox here next. Thx for reporting! 🙏

**Comment by wesbos** [comment]
Okay - so normally how would I get my AWS keys for developing locally? Does it prompt me? Or do I need to sign into that scary place and look for them

**Comment by ryanblock** [comment]
Please stand by, the presence of an `~/.aws/credentials` file was phased out a while back, maybe dependencies are behind.

**Comment by brianleroux** [comment]
It is totally normal to have a `.aws` directory though how you got there can happen in a number of ways because Amazon. Generally credentials are issued at account creation (and then ideal is updated on the regular). You can find them in the AWS console under IAM. I just update the file manually but there are all sorts of tools you can setup for this stuff.

(The dummy creds I pasted will trick it into working local so no need to hunt in there unless you're planning on revisiting AWS dev!)

**Comment by wesbos** [comment]
Oh gotcha- didn't realize that xxx would work. 

Same errors persist when I add that to my config file

**Comment by brianleroux** [comment]
make sure the file is named:  `~/.aws/credentials` (not `config`!)

**Comment by wesbos** [comment]
that worked! Thanks a ton

**Comment by brianleroux** [comment]
awesome, real fix coming soon! if you feel like living on the edge here's a totally undocumented graphql playground crud example with auth! https://github.com/begin-examples/learn-node-graphql/ (I'm working on the docs today tho)

**Comment by ryanblock** [comment]
Wes, first: sorry about this bug, and thanks so much for reporting it! I'm fairly frustrated, personally, because in the last two months I, along with some super smart folks from the [Architect](/architect/architect) community put a lot of time into eliminating the bug vectors that kept creeping up around AWS's credential instantiation. I must have missed something somewhere, because this is the first time I've seen this class of bug in a minute.

ANYWAY, it's now patched in >= `@begin/data@1.1.6`. So your fix options are:
Easy mode: from your app root run `cd src/http/get-todos/ && npm i && cd ../post-todos && npm i && cd ../post-todos-delete && npm i && cd ../../../ && npm run start`
Also easy: delete your current Begin app, create another Begin CRUD app (it's patched in the master repo)

I'm going to continue investigating how this bug was able to exist here and report back on my findings shortly.

**Comment by ryanblock** [comment]
Ok, root cause identified. It goes something like this (briefly):
- Begin (and its open core, [Architect](https://github.com/architect/architect)) exist to empower web developers to create, deploy, and utilize the best of AWS's serverless tech with a dramatic reduction in hassle
  - As such we utilize `aws-sdk` quite a bit (example: persisting data to DynamoDB, which is what powers Begin Data)
- Like many things AWS, `aws-sdk` has some very complex routines around instantiating credentials, which we've done our best to abstract away (or make as easy to manage as humanly possible)
- In this case, I recently introduced some changes that had some incorrect assumptions that `aws-sdk` would populate some environment variables when its credentials were successfully loaded
- The env vars in question were necessary to be passed down into the Lambda execution environment mocked by Sandbox – but they weren't
- As such, `@begin/data` (which relies on `aws-sdk` to talk to DynamoDB) didn't have the env vars necessary to do its thing, and failed

I could go on about the silliness of having to ensure `aws-sdk` is supplied with purposefully invalid credentials just to initialize and talk to local resources, but it is what it is! I missed this edge, and I'm bummed about it.

Anyhow
- **Thank you** for reporting this (and your patience)! It slipped under our test suite, and might not have caught that for quite a while
- The two key libraries now have the offending code completely surrounded in dozens of tests
  - The changes, for the morbidly curious:
    - https://github.com/architect/sandbox/pull/246/files
    - https://github.com/architect/utils/pull/75/files
- These changes shipped a few minutes ago in Sandbox `1.6.1`

🌈
