### ISSUE TITLE
Support for multipart/form-data

### ISSUE THREAD

**Issue by Stegosource** [smallwins/begin-issues#18]
**Expected behavior**
Right now, if I send data to the backend as multiplart/form-data, there is not a clear way to use the data on the backend. I would expect to have some tool or documentation on how to do 

**Steps to reproduce**
Detailed steps to reproduce the behavior:
1. Create an HTTP POST handler:
```js
exports.handler = async function http(request) {
  // do all logging here

  return {
      headers: { "Access-Control-Allow-Origin": "*" },
      statusCode: 200,
      body: 'ok'
    };
}
```

2. Send a fetch request to the endpoint with FormData:
```js
// This is a form's submit event, so target is a form DOM node
onRegister({ target }) {
  const body = new FormData(target);
  fetch(`${API}/register`, {
    method: "POST",
    body
  })
}
```

3. Logging the request.body produces:
```
LS0tLS0tV2ViS2l0Rm9ybUJvdW5kYXJ5dGdCa3BKSTN2cm9CZ2hsSQ0KQ29udGVudC1EaXNwb3NpdGlvbjogZm9ybS1kYXRhOyBuYW1lPSJ1c2VybmFtZSINCg0KdGVtcA0KLS0tLS0tV2ViS2l0Rm9ybUJvdW5kYXJ5dGdCa3BKSTN2cm9CZ2hsSQ0KQ29udGVudC1EaXNwb3NpdGlvbjogZm9ybS1kYXRhOyBuYW1lPSJlbWFpbCINCg0KdGVtcEB0ZW1wLmNvDQotLS0tLS1XZWJLaXRGb3JtQm91bmRhcnl0Z0JrcEpJM3Zyb0JnaGxJDQpDb250ZW50LURpc3Bvc2l0aW9uOiBmb3JtLWRhdGE7IG5hbWU9InBhc3N3b3JkIg0KDQoxMjM0NTY3OA0KLS0tLS0tV2ViS2l0Rm9ybUJvdW5kYXJ5dGdCa3BKSTN2cm9CZ2hsSQ0KQ29udGVudC1EaXNwb3NpdGlvbjogZm9ybS1kYXRhOyBuYW1lPSJyZXBlYXQiDQoNCjEyMzQ1Njc4DQotLS0tLS1XZWJLaXRGb3JtQm91bmRhcnl0Z0JrcEpJM3Zyb0JnaGxJLS0NCg==
```

4. Log the parsed body from `const body = await arc.http.helpers.bodyParser(request)`:
```
{
  base64: 'LS0tLS0tV2ViS2l0Rm9ybUJvdW5kYXJ5WDZzU1BuQWhnNjhjdUpqQQ0KQ29udGVudC1EaXNwb3NpdGlvbjogZm9ybS1kYXRhOyBuYW1lPSJ1c2VybmFtZSINCg0KdGVtcA0KLS0tLS0tV2ViS2l0Rm9ybUJvdW5kYXJ5WDZzU1BuQWhnNjhjdUpqQQ0KQ29udGVudC1EaXNwb3NpdGlvbjogZm9ybS1kYXRhOyBuYW1lPSJlbWFpbCINCg0KdGVtcEB0ZW1wLmNvDQotLS0tLS1XZWJLaXRGb3JtQm91bmRhcnlYNnNTUG5BaGc2OGN1SmpBDQpDb250ZW50LURpc3Bvc2l0aW9uOiBmb3JtLWRhdGE7IG5hbWU9InBhc3N3b3JkIg0KDQoxMjM0NTY3OA0KLS0tLS0tV2ViS2l0Rm9ybUJvdW5kYXJ5WDZzU1BuQWhnNjhjdUpqQQ0KQ29udGVudC1EaXNwb3NpdGlvbjogZm9ybS1kYXRhOyBuYW1lPSJyZXBlYXQiDQoNCjEyMzQ1Njc4DQotLS0tLS1XZWJLaXRGb3JtQm91bmRhcnlYNnNTUG5BaGc2OGN1SmpBLS0NCg=='
}
```
4. Using `Buffer.from` on `request.body` or the parsed `body.base64` (`const decoded = Buffer.from(request.body, "base64")`):
```
------WebKitFormBoundaryOrP0F7TC0dABG7V1
Content-Disposition: form-data; name="username"

temp
------WebKitFormBoundaryOrP0F7TC0dABG7V1
Content-Disposition: form-data; name="email"

temp@temp.co
------WebKitFormBoundaryOrP0F7TC0dABG7V1
Content-Disposition: form-data; name="password"

12345678
------WebKitFormBoundaryOrP0F7TC0dABG7V1
Content-Disposition: form-data; name="repeat"

12345678
------WebKitFormBoundaryOrP0F7TC0dABG7V1--
```

**Desktop**
 - OS: Ubuntu
 - Browser: Firefox/Brave

**Additional content**
Express also does not handle multipart/form-data by default, but I didn't see any solution on how to handle it without a library, and none of the Express libraries work with Begin.

**Comment by ryanblock** [comment]
Thanks for filing this! I'm gonna do my best to take a look at it today, please stand by!

**Comment by Stegosource** [comment]
Not sure if it's also the case for a standard HTML form like:

```
<form method="POST" action="BEGIN_ENDPOINT">
...
</form>
```

But I think by default the form like this would send multipart/form-data

**Comment by ryanblock** [comment]
Sounds like you've already figured out how to get the decoded body payload. Just FYI, an alternative to using the `arc.http.helpers.bodyParser` helper is to run your functions through Architect Functions middleware, which will return your body pre-parsed. See:

```
let arc = require('@architect/functions')

exports.handler = arc.http.async(http)

async function http (req) {
  console.log(req) // will have a parsed body
  return {
    statusCode: 200
  }
}

```

Anyway, to your question: what to do with multipart form data encoded bodies? Great question. The short answer is: anything you want. (I know that's not particularly helpful – but this becomes a Node.js question more than a Begin / AWS question.)

A couple of thoughts, though:
- Do you need to submit `multipart/form-data`-encoded data? By default forms POST encoded with `application/x-www-form-urlencoded`, and I ask because `multipart/form-data` is kind of a pain to work with
  - So if you can just do it as `form-urlencoded`, that's a good way to do things!
  - If it's binary content, you could base64-encode it on the client before submission in order to keep it as form url encoded, but I'd leave that up to you to determine whether you feel it's worth the effort
- In Begin land you don't run a webserver (as you've obviously noticed), so many of the `multipart/form-data`-parsing tools may not be of use. I've tried a few (such as multiparty, multer, etc.), but it's been a while and I don't recall them working (well) with serverless

So, what should you use?
- I'd estimate your best bet is probably `parse-multipart` (because it doesn't seem to want to futz with Node.js http streams): https://www.npmjs.com/package/parse-multipart
- Another option: Lambda multipart parser (I haven't tried, but looks ok): https://www.npmjs.com/package/aws-lambda-multipart-parser

What you're looking for is something that can parse the entirety of a multipart/form payload in one go (instead of attaching to a stream).

Here's a question for you: what would an idea library for this kind of thing look like? (I ask because I've been thinking for a while about maybe writing a multipart/form parser purpose built for serverless, but I haven't had time to figure out what a good version of something like that would even look like.)

**Comment by Stegosource** [comment]
Yeah, I figured about as much. Thanks for looking into this. Today it's not an issue because I'm not sending a file or anything. It may come some day.

https://www.npmjs.com/package/parse-multipart looks promising. I'll give that a looksee :)

As for an ideal library, I think it should take in the request body and kick out the data (maybe as an object?). I'm not sure if you're looking to implement something specifically for Begin or just Lambda. It's hard for me to think outside of traditional Node/Express world. I'm kind of missing how express does middlewares, but that may just be habit.

**Comment by ryanblock** [comment]
Oh one other thing! If you like express, don’t forget you can use it in Begin! See: https://blog.begin.com/make-a-serverless-express-api-with-openjs-architect-cab7a279762b

**Comment by Stegosource** [comment]
WHAT!?!? I had not seen that. Super cool! Thanks.

**Comment by ryanblock** [comment]
No problem. Gonna close this for now but let me know if I can do anything else here!
